import '@/style/global.css'

import { Kanit } from 'next/font/google'
import { Roboto } from 'next/font/google'
import { type Metadata } from 'next'

const kanit = Kanit({
  subsets: ['latin'],
  variable: '--font-kanit',
  weight: ['400', '500', '600', '700'],
})
const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700'],
})
export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${kanit.variable} ${roboto.variable}`}>
      <body className="font-roboto overflow-clip max-h-screen antialiased">{children}</body>
    </html>
  )
}
