version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./texas-show.db:/app/texas-show.db # Mount SQLite database for persistence
    environment:
      NODE_ENV: production
      PAYLOAD_SECRET: d6fff9303740329f8f6f1460 # Set securely in production
      DATABASE_URI: file:./texas-show.db # Path to your SQLite database file
